name: quanlyvosinh
description: Ứng dụng quản lý câu lạc bộ Karate.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.13.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^18.0.1
  shared_preferences: ^2.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
